SELECT COUNT(*) AS TOTAL_ANIMAIS
FROM PET;

SELECT COUNT(VACINA_ID) AS TOTAL_VACINAS
FROM PET;

SELECT COUNT(ID_TIPO) AS QUANTIDADE,
	TIPO_ANIMAL.DESCRICAO AS CATEGORIA
	FROM PET
	JOIN TIPO_ANIMAL ON TIPO_ANIMAL.ID = PET.ID_TIPO
	GROUP BY CATEGORIA;

SELECT COUNT(VACINA_ID) AS VACINAS_TOTAL,
	TIPO_ANIMAL.DESCRICAO AS CATEGORIA
	FROM PET
	JOIN APLICACAO_VACINA ON VACINA_ID = APLICACAO_VACINA.ID
	LEFT JOIN TIPO_ANIMAL ON PET.ID_TIPO = TIPO_ANIMAL.ID
	GROUP BY CATEGORIA
    ORDER BY VACINAS_TOTAL DESC;
