-- Quantidade total de animais registrados
SELECT COUNT(*) AS TOTAL_ANIMAIS
FROM PET;

-- Total de vacinas aplicadas (corrigido para contar a tabela de vacina, não PET)
SELECT COUNT(*) AS TOTAL_VACINAS
FROM APLICACAO_VACINA;

-- Quantidade de animais por categoria
SELECT 
	COUNT(*) AS QUANTIDADE,
	T.DESCRICAO AS CATEGORIA
FROM PET P
JOIN TIPO_ANIMAL T ON T.ID = P.ID_TIPO
GROUP BY T.DESCRICAO;

-- Categoria que mais recebeu vacinas
SELECT 
	COUNT(*) AS VACINAS_TOTAL,
	T.DESCRICAO AS CATEGORIA
FROM APLICACAO_VACINA V
JOIN PET P ON V.VACINA_ID = P.ID
JOIN TIPO_ANIMAL T ON P.ID_TIPO = T.ID
GROUP BY T.DESCRICAO
ORDER BY VACINAS_TOTAL DESC;
