CREATE DATABASE IMOBILIARIA;
USE IMOBILIARIA;

CREATE TABLE `IMOVEIS`(
	`ID` INT NOT NULL,
    `NAME` CHAR(30) NOT NULL,
    `DESCRIPTION` CHAR(50) NOT NULL,
    `ROOM_NUMBERS` INT NOT NULL,
	`SELL_VALUE` FLOAT DEFAULT NULL,
    PRIMARY KEY `PROPERTY_NAME` (`NAME`)
);

SELECT * FROM `IMOVEIS`;
SELECT ID, NAME, DESCRIPTION, ROOM_NUMBERS, SELL_VALUE FROM IMOVEIS;

INSERT IMOVEIS (ID, NAME, DESCRIPTION, ROOM_NUMBERS, SELL_VALUE)
VALUES(1, 'Residência Verde', 'Casa no bairro Primavera', 1, 750);
INSERT IMOVEIS (ID, NAME, DESCRIPTION, ROOM_NUMBERS, SELL_VALUE)
VALUES(2, 'Apartamento Azul', 'Apartamento no bairro Horizonte', 2, 1000);
INSERT IMOVEIS (ID, NAME, DESCRIPTION, ROOM_NUMBERS, SELL_VALUE)
VALUES(3, 'Casa Aurora', 'Casa no bairro Estrela', 2, 2500);
INSERT IMOVEIS (ID, NAME, DESCRIPTION, ROOM_NUMBERS, SELL_VALUE)
VALUES(4, 'Studio Solar', 'Kit-Net no bairro Bela Vista', 1, 500);
INSERT IMOVEIS (ID, NAME, DESCRIPTION, ROOM_NUMBERS, SELL_VALUE)
VALUES(5, 'Sobrado Cedro', 'Duplex no bairro Panorama', 4, 4500);
INSERT IMOVEIS (ID, NAME, DESCRIPTION, ROOM_NUMBERS, SELL_VALUE)
VALUES(6, 'Residência Lima', 'Casa no bairro Jardim América', 3, 900);
INSERT IMOVEIS (ID, NAME, DESCRIPTION, ROOM_NUMBERS, SELL_VALUE)
VALUES(7, 'Chalé Nevada', 'Chalé no bairro Montanha', 2, 1200);
INSERT IMOVEIS (ID, NAME, DESCRIPTION, ROOM_NUMBERS, SELL_VALUE)
VALUES(8, 'Moradia Pinha', 'Alojamento no bairro Encosta', 1, 320);
INSERT IMOVEIS (ID, NAME, DESCRIPTION, ROOM_NUMBERS, SELL_VALUE)
VALUES(9, 'Apartamento Coral', 'Apartamento no bairro Sol Nascente', 2, 600);
INSERT IMOVEIS (ID, NAME, DESCRIPTION, ROOM_NUMBERS, SELL_VALUE)
VALUES(10, 'Apartamento Dourado', 'Apartamento no bairro Jardim das Flores', 3, 3000);
