-- CRIAR BD
CREATE DATABASE GREENHOUSE;

-- DEFINIR BD COMO PADRAO / UTILIZAVEL 
USE GREENHOUSE;

-- CRIAR TABELA/ENTIDADE
CREATE TABLE `PLANTS` (
	`PLANT_NAME` CHAR(30) NOT NULL,
    `SENSOR_VALUE` FLOAT DEFAULT NULL,
    `SENSOR_EVENT` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, 
    PRIMARY KEY  `PK_PLANTS` (`PLANT_NAME`)
);

-- VISUALIZAR TODAS AS OCORRENCIAS EM PLANTS
-- LISTAR TODOS OS REGISTROS DE DADOS
SELECT * FROM `PLANTS`;

-- VISUALIZAR COLUNAS ESPECIFICAS
SELECT PLANT_NAME, SENSOR_VALUE, SENSOR_EVENT FROM PLANTS;

-- INSERIR DADOS NA TABELA/ENTIDADE PLANTS
INSERT INTO PLANTS (PLANT_NAME, SENSOR_VALUE) VALUES('ROSA', 0.2319);

-- INSERIR MULTIPLOS REGISTROS DE UMA VEZ
INSERT INTO PLANTS (PLANT_NAME, SENSOR_VALUE)
VALUES  
      ('cACTUS', 0.2411),
      ('GIRASSOL', 0.3112),
      ('ORQUIDEA', 0.4102),
      ('LIRIO', 0.5566);
      
      -- CONSULTA APLICANDO FILTROS
      SELECT*
      FROM PLANTS
      WHERE PLANT_NAME = 'CACTUS';
      
      -- FILTROS COMPOSTOS COM OPERADORES AND OR XOR ETC
      SELECT*
      FROM PLANTS
      WHERE PLANT_NAME<>'CANNABIS'
      AND SENSOR_VALUE< 0.566 AND SENSOR_VALUE > 0.2411;